### ISSUE TITLE
Unify architecture terminology

### ISSUE THREAD

**Issue by abesto** [openzipkin/openzipkin.github.io#23]
(See #18 for history)

Names for some of the Zipkin components are not clear or overloaded. This was a proposal for an unambiguous terminology.

State: **accepted**
### Goals
- Give components names that describe their purpose
- One name belongs to exactly one component
- Names should have as little coupling to implementation details as possible
### Nouns

The Zipkin components here may be running in one process, in one process per component, or in any setup in between, depending on the specific implementation and deployment strategy.
- _reporter_: anything sending tracing data to Zipkin
- _transport_: used to send tracing data (HTTP, Kafka, Scribe, etc)
- _collector_: Zipkin component that accepts tracing data from _reporters_ over one or more _transports_
- _storage_: Zipkin component providing a read-write API to persisted trace data. Consumed _collector_ and _api_.
- _api_: Zipkin component providing an HTTP API to the _ui_ for accessing tracing data
- _ui_: Zipkin component providing access to tracing data (static single-page app, browser extensions, etc.)
### Used in a sentence

Reporters send trace data via one of several transports to the Zipkin collector, which persists trace data to storage. Later, storage is queried by the API to provide data to the UI.
### Graph

Arrows depict direction of data flow.
![graph](https://cloud.githubusercontent.com/assets/59982/14770085/0ca67162-0a69-11e6-9971-f47854ffb9c1.png)

**Comment by yurishkuro** [comment]
My 2 cents:
* "transport" and "protocol" can be two different things. Transport, as you said, can be HTTP, Kafka, Scribe, etc. Protocol can be JSON, Thrift, etc.
* I've recently began to prefer "recorder" to "reporter" in the client libraries (e.g. OpenTracing Tracers). Reporter implies reporting "out" [of process], which is not always the case, e.g. in unit & integration tests we often use "no-op" or "in-memory" implementations, and "in-memory reporter" sounds weird. The "basictracer" implementations of OpenTracing API are using the term "recorder".
* I am not in favor of "receiver", I think "collector" is a better term. Receiver implies that you always use a push model, Collector can work in both push and pull models, so less implementation specific (granted, openzipkin does not have pull implementations today).
* Everything has an API, it's not a very good name for the component imo. But no strong feelings on this one.
* The arrows in API and UI boxes would make more sense pointing up.

**Comment by abesto** [comment]
Great input, thanks!

> "transport" and "protocol" can be two different things. Transport, as you said, can be HTTP, Kafka, Scribe, etc. Protocol can be JSON, Thrift, etc.

Agree that (HTTP, Kafka, etc.) and (JSON, Thrift, etc.) are different categories. The word "protocol" is not always very strictly defined, and used for various things in various contexts. To me JSON is a data format and HTTP is a protocol (Hypertext Transfer **P**rotocol). Since this is already about nomenclature, this feels like a good time to clear this up. "protocol" is overloaded, but I can't come up with another good word for the (HTTP, Kafka, etc.) category. Suggestions welcome!

> I've recently began to prefer "recorder" to "reporter" in the client libraries [...]

Compatibility with OpenTracing is good methinks. I see the argument for recorder; slightly worried it's a touch too abstract, but I'm totally open to it. Looking for more opinions :)

> I am not in favor of "receiver", I think "collector" is a better term. [...]

I went through the  exact same thought process wrt. passive vs active actor. To me "collector" implies a pull model, but less strongly how than "receiver" implies a push model. Since we came to the opposite conclusion following the same thought process, I feel both are bad names. Racking my brain for another one.

> Everything has an API, it's not a very good name for the component imo.

While it's true everything has an API, this is one of the few names that haven't actively caused confusion (that I know of). That's the reason it's left as is. As with the rest, if better names are floating out there, this is the time to bring them in.

> The arrows in API and UI boxes would make more sense pointing up.

Indeed :) Updated.

**Comment by yurishkuro** [comment]
> and HTTP is a protocol (Hypertext Transfer Protocol).

Indeed, it's just taken from a different perspective, i.e. from a networking TCP/IP stack (looking upwards), HTTP and FTP are different _protocols_. But from the application stack (looking down), HTTP and FTP are different transports.

I think we should be looking at it from the application stack. _Protocol_ is the "language" (data format) in which the messages are expressed. _Transport_ is the way the messages are transmitted/exchanged. Cf http://thrift-tutorial.readthedocs.org/en/latest/thrift-stack.html

**Comment by eirslett** [comment]
+1 from me!

**Comment by adriancole** [comment]
I'm mostly good on this. Don't want to use protocol for json vs thrift (to describe the serialization format). The closest word I can think of is representation, mostly as that's used in hypermedia and also doesn't preclude versions etc. I don't think it would be popular to call json a protocol, if we polled most people.

**Comment by adriancole** [comment]
pitched here and found that the word "reporter" is a good one, and that "transport" is vague in a useful way (i.e. not too specific). Tension seems to be around the word "receiver". It would be nice to have a word that works for active/passive, and also has some symmetry with reporter.

**Comment by adriancole** [comment]
on the component doing storage, "repository" might work better. For example, that's the name of the cassandra class, and also similarly used in a lot of other projects.

**Comment by abesto** [comment]
I prefer "store" to "repository" because in some contexts this will be used in text close to a GitHub repository, and differentiating between the things that "Zipkin repository" can mean is cumbersome.

For receiver/collector, here are a couple more ideas: ingest (would prefer a simpler word), consumer (implies passive over active), gateway (overloaded, implies more complexity than exists), ferry (because sometimes it's pushed, sometimes it's pulled, even though modern ferries have their own power), entry, entrance, ingress (would prefer a simpler word)

**Comment by adriancole** [comment]
> I prefer "store" to "repository" because in some contexts this will be
used in text close to a GitHub repository, and differentiating between the
things that "Zipkin repository" can mean is cumbersome.
Good point

> For receiver/collector, here are a couple more ideas: ingest (would
prefer a simpler word), consumer (implies passive over active), gateway
(overloaded, implies more complexity than exists), ferry (because sometimes
it's pushed, sometimes it's pulled, even though modern ferries have their
own power), entry, entrance, ingress (would prefer a simpler word)

From a component POV, I'm using the word span consumer for the act of
sinking spans. Ex java has a consumer type which fits pretty well. However,
it doesn't really address who is pushing the data (in this case the HTTP or
Kafka component). For this reason, I might prefer not using consumer.

Kafka ingester HTTP ingester
Vs
Kafka ingresser?

I so far like ingester for the component that handles the server side of
the transport.

Ex applications report to Kafka, the ingester decodes spans and stores
them, subject to sampling policy.

**Comment by eirslett** [comment]
I think "collector" is a pretty good term for the process that receives spans, either active or passive. I don't think it matters that much whether it's a pull or push model.
Status quo is also that it's called collector, so that's one less thing to rename.

**Comment by abesto** [comment]
Brainstorming with @chimericalidea.

 * Storage: **CRUDS**? Nice, standard, and avoids the "database = storage" confusion
 * Reporter vs Recorder: one new argument came up here: there are a lot of steps between this component and the database, which makes "recorder" feel premature. OTOH since there's agreement within OpenTracing to use **recorder**, we propose we go with it for less fragmentation across the distributed tracing landscape.
 * Transport vs protocol: we have both of course, especially if you change your viewpoint; I feel the main confusion here was caused by having both refer to the same component. Let's call it **transport** (removed "protocol" from the description of "transport").
 * Receiver / collector / ingest[eo]r: 1 vote for receiver (@abesto), 2 votes for collector (@yurishkuro, @eirslett), 1 votes for ingestor (@adriancole). The three of us don't feel strongly, except for the point that if we use a single word consistently, it's gonna be fine. We propose we go with **collector** for both the vote count and status quo.

I've updated the description of the issue to reflect these proposals. Let's do a final round of +1 / concerns.

**Comment by yurishkuro** [comment]
+1 for "store". The "database" box could be a dotted line below the Store (e.g. for in-memory stores).

+1 the rest

**Comment by adriancole** [comment]
Hoping this doesn't go bikeshed, but..

Do we need to define the target of a storage component? (Knowing it might
be a proxy!). I'd rather not introduce a word than introduce a verb as a
noun.

Ex persists data to a store via a storage component.

Examples where we don't add a word for the storage target:

Ex persists data via a storage component. Queries data via a storage
component.

Or even: persists data to storage. Queries spans from storage.

Storage is the least concerning part of the architecture as most know what
that word means. Remember our properties are already prefixed with storage.

I like that we've gotten so far, and hope we can seal the deal with the
least explaining. Ex if we can manage to only define surprising things, we
use less words and pictures more wisely.

**Comment by adriancole** [comment]
ps to find a way to unlock this, especially since more important naming things are ok'ed at this point.

#### Recorder vs Reporter
I feel awkward about favoriting OpenTracing (as it implicitly un-favorites HTrace and others who aren't involved or engaged). It also seems forged and premature to choose a term that doesn't exist on opentracing's website. Anyway..

* +0 on recorder
  * recording doesn't really imply the source of data pipeline in any way. It defines the act of snapshoting the trace info, which is outside the scope of zipkin's system. (ex it is before transport and includes sampling concerns we don't define). I'm only +0 and not -1 as a concession to be able to progress.
* +1 on reporter
  * I do think reporter is a good word for the act. I also checked this with someone with no dog in the race, and he understood it.

#### Database vs Store
Remember.. this term only affects the arch diagram and not code.

* +0 for database, since it is easy to understand, and causes little harm. `collector -> storage -> database`
* +1 to leave this part unnamed, as it is relatively common to. Ex just stop at  `collector -> storage`
* -1 for "store" as the diagram just looks chatty `collector -> storage -> database`

For example, leaving out the "database" word shortens this..

> Reporters send trace data via one of several transports to the Zipkin collector, which persists trace data to a database via the storage component. Later, storage is queried by the API to provide data to the UI.

To this:
> Reporters send trace data via one of several transports to the Zipkin collector, which persists trace data via the storage component. Later, storage is queried by the API to provide data to the UI.

If folks are fine with this, I'd love for us to be able to move on and actually correct our docs accordingly. What say you?

**Comment by anuraaga** [comment]
FWIW, I agree with @adriancole's post - +1 reporter, +1 leave out database/store/whatever. In particular, don't like database much since the word tends to have an SQL connotation and feels less flexible than we'd like.

**Comment by mansu** [comment]
> reporter: anything sending tracing data to Zipkin
> transport: used to send tracing data (HTTP, Kafka, Scribe, etc)

I prefer the word span logger(logger) to reporter. The word logger already has a well understood meaning and it applies very well here. Java folks implicitly understand that a logger can send messages to multiple backends after formatting the message accordingly.

I am ok with transport although a protocol may be more appropriate here.

> receiver: Zipkin component that accepts tracing data from reporters over one or more transports
> storage: Zipkin component providing a read-write API to the underlying database. Consumed receiver and api.
> database: ElasticSearch, MySQL, Cassandra, etc

+1 for collector instead of receiver. I am with @eirslett here.

I think we should not separate out storage vs database and keep them as a single entity since one doesn't make sense without the other. I think we should call the combined entity a span store. So, +1 for @adriancole's comment that we should leaving storage layer unnamed.

**Comment by jtrobec** [comment]
FWIW, I'm happy with the consensus as well, particularly with leaving 'database' out of it. If there are no particular requirements beyond the storage abstraction then seems best to leave it open-ended...doing otherwise may just cause confusion.

**Comment by adriancole** [comment]
Harvesting some explanation after a chat with @mansu on gitter made me realize a lot of context isn't explicit.

One of the goals I was hoping for was to define the least responsibility needed to integrate with zipkin. In many tracers, zipkin is a choice, and the actual code to integrate with zipkin can be as little as a couple classes (data converter and transport logic). That component is the most interesting piece, and it really defines how instrumentation works with zipkin's data pipeline. Most of the vocab here is about that architecture piece.. ex what is the thing that connects app instrumentation to zipkin?

For example, logger is a good word, and generally describes most of a tracer in a familiar way. This is nice about describing the general tasks of instrumentation, but imprecise about the data flow/architecture. That said, if you are using a log transport, like scribe.. gosh logger sounds attractive!

Anyway, what's called reporter is usually a single function that sends a bundle of spans across the transport.

Ex. Reporter has the following analogs in existing projects:
* Brave's [SpanCollector.sendSpans](https://github.com/openzipkin/brave/blob/master/brave-spancollector-http/src/main/java/com/github/kristofa/brave/http/HttpSpanCollector.java#L93)
* HTrace's [Transport.send](https://github.com/apache/incubator-htrace/blob/master/htrace-zipkin/src/main/java/org/apache/htrace/Transport.java#L49)
* Ruby's [Tracer.flush](https://github.com/openzipkin/zipkin-tracer/blob/master/lib/zipkin-tracer/zipkin_kafka_tracer.rb#L29)
* Sleuth's [Reporter.report](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/SpanReporter.java#L30)
* Pyramid's [transport_handler](http://pyramid-zipkin.readthedocs.org/en/latest/configuring_zipkin.html)

The most interesting one is probably Finagle, because it does use logging vocab. Ex [Tracer.logSpans](https://github.com/twitter/finagle/blob/develop/finagle-zipkin/src/main/scala/com/twitter/finagle/zipkin/thrift/RawZipkinTracer.scala#L195). If you look carefully, though, that's because it is literally using a logging transport, Scribe. I'm not sure if this name will persist once finagle's zipkin support disconnects from scribe via https://github.com/twitter/finagle/issues/465

**Comment by abesto** [comment]
Looks like we might have a decision?

Book-keeping:
 * Updated the description with *reporter, collector, storage*.
 * Moved Database out of the Zipkin box, removed it from the list of Zipkin components.

**Comment by adriancole** [comment]
:shipit:

**Comment by eirslett** [comment]
:+1:

**Comment by abesto** [comment]
Done and done! We'll get started on a PR to implement the new names in documentation.

**Comment by adriancole** [comment]
re-opening this, as the outputs (like the diagram above) haven't been integrated, and I keep referring folks to a closed issue :P

**Comment by adriancole** [comment]
step 1 https://github.com/openzipkin/openzipkin.github.io/pull/59

**Comment by abesto** [comment]
Skimming http://zipkin.io, it looks like these changes are rolled out across the doc site. If we need to put in extra work on internal names in code, I'd suggest tracking those changes in the respective repositories of the code. Close? @adriancole

**Comment by adriancole** [comment]
ayup!
